In [1]:
from gaussians import Gaussian

In [2]:
import torch

In [3]:
from ubvi import UBVI

In [4]:
target_pdf = lambda x: torch.exp(-(x ** 2).sum())

In [5]:
test = UBVI(target_pdf, Gaussian(1), num_opt_steps=1000, n_samples=100)

In [6]:
test.build(10)

Initializing component 1... 
          Iteration           |          Best param          |        Best objective        
              0               |tensor([-148.4195,    0.0000])|       tensor(-0.7416)        
              9               |tensor([-115.4368,    0.0000])|       tensor(-1.1168)        
Initialization of component 1 complete, x0 = tensor([-115.4368,    0.0000])
Optimizing component 1... 
Optimization of component 1 complete
Updating weights...
Weight update complete...
Component 1:
Hellinger Dist Sq: tensor(0.2985, grad_fn=<RsubBackward1>)
Params:{'mus': tensor([[-115.4368]], grad_fn=<SliceBackward>), 'sigmas': tensor([[22029.4062]], grad_fn=<ExpBackward>)}
Weights: tensor([1.])
Initializing component 2... 
          Iteration           |          Best param          |        Best objective        
              0               |tensor([8209.6611,   10.0874], grad_fn=<CatBackward>)|tensor(-3.4106, grad_fn=<NegBackward>)
              9               |tensor([2.0698e

/Users/ybiktairov/Documents/Skoltech/Sk_Bayes/project/UBVI/source/ubvi.py:98: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  log_denom = 0.5 * torch.log(1. - torch.exp(torch.tensor(2 * lgh)))


Optimization of component 2 complete
Updating weights...
tensor([[1., nan],
        [nan, nan]], grad_fn=<CopySlices>)


RuntimeError: cholesky_cpu: U(2,2) is zero, singular U.

In [8]:
test_a = torch.tensor([[1, 2], [1, 2]])

In [10]:
test_b = torch.tensor([2, 3])

In [11]:
test_b.expand_as(test_a)

tensor([[2, 3],
        [2, 3]])

In [10]:
torch.tensor(3, dtype=torch.float32)

tensor(3.)

In [15]:
test = torch.tensor([1., 2])

In [16]:
test.requires_grad

False

In [17]:
test.requires_grad_()

tensor([1., 2.], requires_grad=True)

In [18]:
test.requires_grad

True

In [8]:
x = torch.tensor([[1., 2], [2, 3]], requires_grad=True)

In [9]:
torch.optim.Adam([x])

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0
)

In [9]:
x.dot(torch.Tensor([1, 2]))

RuntimeError: 1D tensors expected, got 2D, 1D tensors at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:774